import type { Metadata } from 'next'
import MuiProvider from './providers/mui-provider'
import { roboto } from './fonts/RobotoFont'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.variable}`}>
                <MuiProvider>{children}</MuiProvider>
            </body>
        </html>
    )
}
